### ISSUE TITLE
Issue via EVE App

### ISSUE THREAD

**Issue by JacVid** [Sunoo/homebridge-aqicn#124]
Hello,

while using EVE app to check the air quality after installing the HomeBridge Plugin, I get a warning issue (nothing via Home App).

It says : Accessory is disable. Check user manual.

Thank you.

![IMG_0710](https://user-images.githubusercontent.com/45730690/115679170-91946780-a352-11eb-8299-86381642fa2e.PNG)

**Comment by Sunoo** [comment]
I’ll take a look soon. I don’t typically use the Eve app, and not speaking French complicates this a bit too.

Do you see any errors in the Home app? Or is it Eve only?

**Comment by JacVid** [comment]
No error in Home App, only with Eve App ;)

And for the french translation, the warning says : Accessory is disable. Check user manual.

**Comment by Sunoo** [comment]
Okay, I remember what that is now, just was confused by seeing it in Eve.

I set the Active status only when the data is from within the past hour. If it’s older than that, the sensor is marked inactive, and I guess that is how Eve chooses to display that status.

**Comment by JacVid** [comment]
Thanks for having a lokk at it ;)

For information, my setting for this plugin is : "polling_minutes": 30

**Comment by Sunoo** [comment]
I could probably make this configurable too if there is a desire.

**Comment by JacVid** [comment]
My only concern is to get this error away :p

If a specific setting is required, why not.

**Comment by Sunoo** [comment]
Okay, I’ll add a feature when I next have a minute. Will be something like inactive_minutes and setting it to 0 will just show it always as active. Probably.

I just moved though, so most of my stuff is boxed, so I can’t promise when it’ll be.

**Comment by JacVid** [comment]
Hello, any news regarding this topic ?

Thank you.

**Comment by Sunoo** [comment]
Honestly, between getting the new house in order and my day job being crazier, I haven’t had much time or energy for personal coding projects. Hoping to get to this soon.

**Comment by Sunoo** [comment]
Included in v1.2.1. Sorry for the delay.

**Comment by JacVid** [comment]
Thank you very much, it works fine ;)
