### ISSUE TITLE
Unhandled exception with erroneous AQI API token

### ISSUE THREAD

**Issue by vsenn** [Sunoo/homebridge-aqicn#135]
First, thank your for the plug-in.

Does it look like an unhandled exception? 
For me it does and violates the Verified plugin requirement #6 (The plugin must not throw unhandled exceptions, the plugin must catch and log its own errors.) here https://github.com/homebridge/homebridge/wiki/verified-Plugins

(node:9126) UnhandledPromiseRejectionWarning: Error: Invalid key
    at checkError (/homebridge/node_modules/homebridge-aqicn/node_modules/@shootismoke/dataproviders/lib/providers/aqicn/fetchBy.js:35:19)
    at /homebridge/node_modules/homebridge-aqicn/node_modules/fp-ts/lib/EitherT.js:52:116
    at /homebridge/node_modules/homebridge-aqicn/node_modules/fp-ts/lib/Task.js:138:44
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9126) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:9126) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Could you please fix it. Thanks a lot!

**Comment by Sunoo** [comment]
This should be fixed in v1.2.0.
