### ISSUE TITLE
Truncate Homebridge manufacturer up to 64

### ISSUE THREAD

**Issue by vsenn** [Sunoo/homebridge-aqicn#136]
Another enhancement request is to truncate the long names of AQI station's names. In my case it is - Station provided by "Moscow State environmental monitoring (Государственный экологический мониторинг в Москве)"  which raise a warning below:
[homebridge-aqicn] This plugin generated a warning from the characteristic 'Manufacturer': characteristic was supplied illegal value: string 'Moscow State environmental monitoring (Государственный экологический мониторинг в' exceeded max length of 64. See https://git.io/JtMGR for more info.

Thank a lot in advance!

**Comment by Sunoo** [comment]
Odd, I do have code to truncate station names already. I’ll have to take a look later to see why it’s apparently not working correctly for you. Maybe my code has a bug with handling Cyrillic characters?

**Comment by Sunoo** [comment]
This should be fixed in v1.2.0.

**Comment by vsenn** [comment]
It is surely fixed and now it's perfect! Thank you a ton, man!
